[package]
name = "news_dao"
version = "0.1.0"
authors = ["Simon <zengweiking@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
